# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: network-of-assistants
description: Helm chart for the Network of Assistants
maintainers:
  - name: tfeltin
    email: tfeltin@cisco.com

type: application

version: 0.1.1

appVersion: "0.1.1"
