[project]
name = "slim"
version = "0.5.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "slim-bindings>=0.5.0",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = ["slim/"]
