{{- if not .Values.networkOfAssistants.webSurferAssistant.llm.remoteAPISecret.existingSecret }}
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "network-of-assistants.web-surfer.llmRemoteAPISecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "network-of-assistants.web-surfer.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.networkOfAssistants.webSurferAssistant.llm.remoteAPISecret.secretKeys.address }}: {{ .Values.networkOfAssistants.webSurferAssistant.llm.remoteAPISecret.address | b64enc }}
  {{ .Values.networkOfAssistants.webSurferAssistant.llm.remoteAPISecret.secretKeys.key }}: {{ .Values.networkOfAssistants.webSurferAssistant.llm.remoteAPISecret.key | b64enc }}
---
{{- end }}
